# Generated by Django 5.1.7 on 2025-03-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_position_remove_voter_email_alter_candidate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='main.position'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'candidate')},
        ),
    ]
