# Generated by Django 5.1.7 on 2025-03-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='language',
            new_name='email',
        ),
    ]
