# Generated by Django 5.1.7 on 2025-03-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_language_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='party',
            new_name='Department',
        ),
    ]
